//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridge.Repository.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSequence
    {
        public int OrderSequenceId { get; set; }
        public int OrderSequenceVal { get; set; }
    }
}
