//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridge.Repository.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int ProductImageId { get; set; }
        public int ProductID { get; set; }
        public byte[] ProductImage1 { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
